
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvxeyudywurpxwyjipve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2eGV5dWR5d3VycHh3eWppcHZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTQyMjAsImV4cCI6MjA1OTIzMDIyMH0.bFmxBjjpoKWZNdslxGUxwSPbMyCHMwugjngMAUVkV9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
